### ISSUE TITLE
Nether Core 1.3.0 Crash on Startup

### ISSUE THREAD

**Issue by Darkosto** [RenEvo/nethercore#21]
Hello, I seem to be getting a crash on startup after installing 1.3.0. It appears to be Nether Core, but please let me know if it's another mod :)

http://pastebin.com/1aQp7qRb

Thank you for your help!
Darkosto

**Comment by renevo** [comment]
Checking into it!

**Comment by renevo** [comment]
Yup, looks like an issue with the Mantle 0.7 to 0.9, will get a hotfix out asap.

**Comment by Darkosto** [comment]
Thank you very much!! :)

**Comment by renevo** [comment]
Hmm, Mantle doesn't seem to be the issue, I did update my MCP mappings from stable_20 to stable_22, might be something with that.

**Comment by renevo** [comment]
Ok, publishing all the things in a sec.

**Comment by renevo** [comment]
Ok, published release: https://github.com/RenEvo/nethercore/releases/tag/v1.3.1

You can download direct from there, or wait for the update on curse (waiting on approval).

Thanks for the bug report, and sorry about the crash, adding that step to test on my list now :+1:

**Comment by Darkosto** [comment]
It works! Thank you so much for the quick response :D

**Comment by renevo** [comment]
Thanks for reporting, and sorry for the derp. Happy Nethering!
