### ISSUE TITLE
Port on 1.7.10

### ISSUE THREAD

**Issue by Tsyklop** [RenEvo/nethercore#23]
Please. Port on 1.7.10

**Comment by renevo** [comment]
Any features in particular?

**Comment by Tsyklop** [comment]
@RenEvo I did not understand the question. you ask the reasons for porting to 1.7.10?

**Comment by renevo** [comment]
Which features would you like ported, or is it just a general request?

**Comment by Tsyklop** [comment]
general request and add support MineTweaker for Nether Furnace...

**Comment by renevo** [comment]
MineTweaker should work by just changing furnace recipes, since it uses the same.

**Comment by renevo** [comment]
Going to close this for now, but might investigate this later.

At this time, I don't plan on backporting, as that would require quite a bit of additional work, and I want to spend that time getting ready for 1.9.
