### ISSUE TITLE
Nether Mob Configurable Restrictions

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#27]
Ghast, Blaze, Wither Skeleton, Skeleton, Zombie Pigmen can only spawn on configurable blocks, by default:
- Gravel
- Netherrack
- Nether Bricks
- Soul Sand

This is to help promote the building of bases in the Nether, and not getting over ran with mobs that shouldn't spawn inside player built structures.

As an addendum, we should probably look at adding support for Biomes O Plenty and Natura, since they both add a decent amount of surface blocks to the Nether.

**Comment by IronyAtFive** [comment]
That would make sense to support other biome mods. For the spawn rate, it could be a good idea to get it work with a light source, but that would be alot of work with the vanilla mobs. I would try that if I could, but I don't have enough knowledge in mod making....

**Comment by renevo** [comment]
Working with light sources actually isn't a huge issue. I did this almost exact same thing awhile back ago with another mod and actually did the feature request to prevent mob spawning into Forge. Light level could be added to the checks/balance system for mob spawning.

Will definitely look into adding this feature then :)

**Comment by IronyAtFive** [comment]
Pleasure to help, I see alot of potential in your mod!

**Comment by IronyAtFive** [comment]
Would it be easier to get the mob spawn rate with with light source at the place of surface block?

**Comment by renevo** [comment]
Can do either actually :)

basically, configuration would be:

mobid: 
blacklist: [minecraft:gravel, minecraft:sand]
whitelist: []
minLight: 7
maxLight: 15

or something of the like.

**Comment by IronyAtFive** [comment]
Maybe they should spawn on anything like normal, except when the lighting amount is safe. For nethergrowth, why not reducing it to something like 1/4 normal spawn rate with no light? Don't forget also Ghast spawn everywhere it fit
