### ISSUE TITLE
Update to 1.10.2

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#29]

**Comment by renevo** [comment]
Having issues with the getQuantityDroppedWithBonus due to the removed parameter from the method, will be seeing if I can fix this.

**Comment by IronyAtFive** [comment]
If you need a tester, it would be a pleasure. Your work get my thaumcraft more interesting, as the Nether is a flux free place.

**Comment by renevo** [comment]
Thanks, i just recently posted up an alpha release here and on curseforge.

Feel free to post bugs (even known ones) to that I can track them getting fixed :)

**Comment by IronyAtFive** [comment]
Saw it not long ago, I use curse app. Gonna get on it tonight a bit. Still gotta figure the nether spore recipe

**Comment by renevo** [comment]
Going to wait on the 1.9.4 upgrade until Forge is more stable.

**Comment by renevo** [comment]
Tinkers looks like it is stable enough to try an upgrade, will work on it this week.

**Comment by renevo** [comment]
There are a lot of methods around rendering marked as deprecated, need to look at these.

Additionally, the Wall issue still exists (breaking shows purple not found texture).

Other than that, most things went through fine.

**Comment by renevo** [comment]
Updated this task to 1.10.2.

1.9 and 1.9.4 will remain in beta state and will not be updated beyond, 1.10.2 will be the sole focus.

**Comment by renevo** [comment]
New blocks haven't made it into the mappings file yet, which isn't a surprise since the latest mappings are the same as the 1.9.4 mappings.

**Comment by renevo** [comment]
Totally forgot to checkin like most of the files for the 1.10 add, committed them here: c336a337847a6bfdcfbdeb6f4296a19b24bc528f

**Comment by renevo** [comment]
Must remember to do a obsfucated build when uploading...

**Comment by renevo** [comment]
Pushing final build now, totally forgot it was a beta...
