### ISSUE TITLE
Soul Glass doesn't render texture

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#31]
It is completely invisible...

**Comment by IronyAtFive** [comment]
Could it be a problem with how it decide the translucent side?

**Comment by renevo** [comment]
Glass rendering changed a bit in 1.9, just need to figure out the change and if it is in the model or the code.

**Comment by IronyAtFive** [comment]
Right, I might take a peak at the code if I manage to get the time. That packet tracer homework is a pain, so I might won't have the time to find and compare the code
