### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by MysticAura** [RenEvo/nethercore#39]
This mod looks promising. However, when I added it to my pack it crashes on launch

MC Version: 1.10.2
Mod Version: 1.10.2-2.0.2
Forge Version: 12.18.0.2007

[Crash Log](http://pastebin.com/n3e3ifWW)

**Comment by renevo** [comment]
Think i uploaded a non-obsfucated build... building again :(

**Comment by renevo** [comment]
Commit c336a337847a6bfdcfbdeb6f4296a19b24bc528f fixes this issue with a rebuild, check the releases tab, or re-download from curse (in a bit).

**Comment by renevo** [comment]
@MysticAura thanks for reporting as well !
