### ISSUE TITLE
getPickBlock Not Being Overriden

### ISSUE THREAD

**Issue by ChloeDawn** [RenEvo/nethercore#45]
Middle clicking ore's in creative causes them to not be picked properly, and it also causes them to not display correctly in WAILA.

![2016-11-05_17 56 46](https://cloud.githubusercontent.com/assets/9869940/20032419/3c7b14e0-a381-11e6-858f-70ad25ba55dc.png)

I was asked to report this by @TehNut, who maintains an [up-to-date fork of WAILA](https://github.com/TehNut/HWYLA).

**Comment by renevo** [comment]
Thanks, will get this in the next release.
