### ISSUE TITLE
Other mod ore generators spawns

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#46]
Create a unique generator for different ores

- [ ] Copper (iron base)
- [ ] Tin (iron base)
- [ ] Silver (gold base)
- [ ] Lead (gold base)
- [ ] Osmium (iron base)
- [ ] Uranium (emerald base)
- [ ] Aluminum (gold base)

Should use the new configurations.

Ore generators should only be available with ore dictionary lookup for the over world ore.

**Comment by snurre0** [comment]
Sorry to ask, but if I understand this correctly(when it's released), nethercore will spawn i.e silver ores if I use a mod that adds silver ores to the overworld? 
If that's the case, this is Awesome! :D

**Comment by renevo** [comment]
@snurre0 yes, that is correct :)

**Comment by TheRandomLabs** [comment]
Could you also add support for the following? If not, it's fine, but it would be nice.

Peridot, Ruby, Sapphire (Project Red)
Iridium (IC2)
Ferrous, Platinum (Thermal Foundation)
