### ISSUE TITLE
Nethercore slabs rendering bug?

### ISSUE THREAD

**Issue by snurre0** [RenEvo/nethercore#47]
Hi,

I have a small problem with the slabs i nethercore.
All four slab types appear the same if it's placed in the upper half of a block, with just air in the halv block below it.

Here's a picture. I've made one row with different slab types.
First a stack of 6 slabs of each, then double slabs of each, then two single slabs at the lowest half block, and then one halv block upwards for the next four.

![2016-11-08_23 17 13](https://cloud.githubusercontent.com/assets/12727805/20119824/50966610-a60a-11e6-8d19-96ce578e9a49.png)

As you can se, every slab that is placed in the upper half of a block, gets rendered as a regular nether stone slab(I don't remember the exact name of it).

Actially, when I place the slab, it renders correctly just the first miliseconds, then it changes.

I have not managed to reproduce this in a single player, only on a multiplayer server.
Testet on a server with only nethercore(and Mantle) installed, no other mods.

MC 1.10.2
Forge 12.18.2.2114
Nethercore 2.0.3
Mantle 1.1.1

Best regards,
Morten

**Comment by snurre0** [comment]
Forgot to mention, when I break the slabs, they are back to the four different types again.

**Comment by renevo** [comment]
Think this might just be a texture bug, will get it fixed.
