### ISSUE TITLE
JEI compatibility issue

### ISSUE THREAD

**Issue by ghost** [RenEvo/nethercore#48]
Forge version: 1.10.2-12.18.2.2120
Nether Core version: 2.0.3
JEI version: 3.13.2.360

The Nether Furnace is listed twice with the second one missing its texture in the JEI item list.

**Comment by ghost** [comment]
The-Fireplace [fixed the issue](https://github.com/The-Fireplace/Adobe-Blocks/issues/7), maybe he can help.

**Comment by ghost** [comment]
The Furnace without texture is the lit one which can't be crafted. I worked around the issue by putting it on the JEI blacklist.

**Comment by renevo** [comment]
Thanks for the list, hadn't seen a good way to do that yet with JEI :)
