### ISSUE TITLE
Startup Crash - 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [RenEvo/nethercore#52]
https://gist.github.com/P3rf3ctXZer0/e3ad9602d06f6c591d31688fc3253b24

**Comment by renevo** [comment]
Thanks, seems like an odd one, will investigate

**Comment by Sinhika** [comment]
Mod interaction bug: both NetherCore and my Netherrocks are registering a tile entity as "container.nether_furnace".  Looks like we both need to put mod prefixes on our names. See [https://github.com/Sinhika/Netherrocks/issues/5](url)

**Comment by Sinhika** [comment]
Fixed at my end.

**Comment by renevo** [comment]
Nice catch, will also update on my end when I upgrade.

**Comment by EliSauder** [comment]
I am trying to put together a mod pack and whenever I try to load this mod (minecraft version 1.10.2) it crashes before it can load. Is there a specific forge version I should run?

**Comment by EliSauder** [comment]
Scrap that I'm just being stupid and didn't have tcon and mantel loaded.
