### ISSUE TITLE
TOP mistaking ores.

### ISSUE THREAD

**Issue by quixQuery** [RenEvo/nethercore#55]
1.10 latest version of Nether Core and The One Probe. TOP picks up redstone, and emerald ores as coal ore.

![](https://cdn.discordapp.com/attachments/298861893513379850/323964869709922304/2017-06-12_18.12.57.png)

**Comment by renevo** [comment]
Thanks for the report, think this is related to another issue as well.

**Comment by renevo** [comment]
Possible duplicate of #45
