### ISSUE TITLE
Nether Coal

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#6]
2x burn time.

Not sure how to make this just yet...

**Comment by renevo** [comment]
Thoughts on this was to have Nether Growth spread to a Nether Coal Ore and turn it into Nether Coal Ore..... Which is better.

**Comment by renevo** [comment]
This might need some tweaks to the Nether Growth spread logic to keep it somewhat sane as I want to add more things to how it can spread to other things.

**Comment by Faelysse** [comment]
This could use some rework, as it's weird how the Coal Ore block drops 2 Coal, but Nether Coal Ore drops only one, thus making it pretty useless to farm Nether Coal Ore, as 2x heat time is the same as 2x drops. Maybe increase the droprate of Nether Coal Ore to 2x also, or increase the heat time to 3x?
