### ISSUE TITLE
Nether Fuel

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#7]
Alternative, should be on par with Ethanol.

Not sure how to make this just yet...

**Comment by renevo** [comment]
Not going to do this for now.

**Comment by IronyAtFive** [comment]
You don't need a new fuel, as the furnace don't need it. my opinion

**Comment by renevo** [comment]
It was more for engines (BC) or generators (IC2) than for furnaces, Nether Coal fills the gap for furnaces, as well as the vast amount of coal generation in the Nether.

**Comment by IronyAtFive** [comment]
As I think about it... it is usefull for minecart. Do you think it would be a good idea of a netherfurnace minecart? it would have a base power if use in the nether, plus a slot in it to keep lava for unlimited propulsion without redstone tracks

**Comment by renevo** [comment]
hmm, can you post another issue with that? Can think about how that would work and balance things out :)
