### ISSUE TITLE
Nether Dungeon

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#9]
Like overworld, except nether-ry.

What will actually spawn from these?

**Comment by IronyAtFive** [comment]
Pigmen wouldn't make sense. Wither skeleton would be a good idea. And they could be made out of NetherCobble. And how about some compact Netherack in the treasure? and a epic-ly rare netherstar?

**Comment by renevo** [comment]
Idea validated! Wil put it on the todo list :)
